apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <%= repositoryName %>
  namespace: <%= repositoryName %>
spec:
  secretName: <%= repositoryName %>
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "<%= subdomainName %>.trueberryless.org"
