apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <%= repositoryName %>
  namespace: <%= repositoryName %>
spec:
  rules:
    - host: <%= subdomainName %>.trueberryless.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: <%= repositoryName %>
                port:
                  number: 80

  tls:
    - hosts:
        - <%= subdomainName %>.trueberryless.org
      secretName: <%= repositoryName %>
