apiVersion: v1
kind: Service
metadata:
  name: <%= repositoryName %>
  namespace: <%= repositoryName %>
  annotations:
    cert-manager.io/issuer: acme-issuer
spec:
  selector:
    app: <%= repositoryName %>
  ports:
    - name: http
      port: 80
