name: "Pull Request Labeler"
on:
  - pull_request_target
  - push

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure labels exist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh label create "🚨 action" --description "Changes in GitHub workflows or actions" --color "A75AD5"
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yaml
          sync-labels: true
