name: Sort Repository Files

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "repos.json"

jobs:
  sort-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Sort Files
        run: |
          import json

          def sort_files_by_target_path(files):
              def sort_key(file_obj):
                  target_path = file_obj.get("targetPath", "")
                  components = target_path.split('/')
                  is_directory = target_path.endswith('/')
                  return (components, not is_directory)

              return sorted(files, key=lambda f: (sort_key(f), f["targetPath"]))

          input_file = "repos.json"

          with open(input_file, "r") as f:
              data = json.load(f)

          if "repositories" not in data:
              print(f"Error: {input_file} does not contain a 'repositories' key.")
              return

          for repo in data["repositories"]:
              if "files" in repo:
                  repo["files"] = sort_files_by_target_path(repo["files"])

          with open(input_file, "w") as f:
              json.dump(data, f, indent=2)
              f.write("\n")

        shell: python

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PUBLIC_GITHUB_TOKEN }}
          commit-message: "[ci] sort repos.json files"
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: ci-sort-repo-files
          delete-branch: true
          title: "[ci] sort repos.json files"
          body: "This PR was automatically created to sort the files in the `repos.json` file."
          labels: 🤖 bot
          assignees: trueberryless
          draft: false
